### ISSUE TITLE
Boostrap/Package: How to adapt for distribution-specific shared library names?

### ISSUE THREAD

**Issue by mhthies** [just-buildsystem/justbuild#13]
I'm trying to package *justbuild* for ArchLinux, linking against native shared libraries, provided by ArchLinux packages, as far as possible. After working around the other issues (#9, #10, #11, #12), I encountered the problem that the prebuild shared libraries, provided by the official ArchLinux packages, have completely different names than expected by the *justbuild* build. So, the linker arguments need to be adjusted accordingly. In addition, the "well-known" proto files, provided with the protobuf compiler, are located in `/usr/include/google/protobuf` instead of `/usr/proto/google/protobuf` on ArchLinux.

I patched the TARGET files in `etc/import.prebuild` to adjust for these differences. However, this resulted in [a rather large patch](https://github.com/mhthies/justbuild/commit/b6abac928393d4e42e81386f6dfa31867a042f08) and left me with the question, whether this is the expected way of solving this. Am I supposed to include these changes as patch file with my packaging recipe or is there another way?

**Comment by aehlig** [comment]
Unfortunately, I don't know a better way. In the end, it is necessary that the tool know the correct linker flags. As the targets files are JSON, a programmatic rewrite (using tools like `jq` or a small script similar to the rewrtiting of the `repos.json` in `bootstrap.py`) might be another option&mdash;provided the needed information can be obtained easily via tools like `pkg-config`.

Concerning the large part of the patch that changes related to the different names of the CLI11 header files, I guess a `TREE` reference would be the right thing to do here. I'll prepare a patch.

**Comment by aehlig** [comment]
> Concerning the large part of the patch that changes related to the different names of the CLI11 header files, I guess a `TREE` reference would be the right thing to do here. I'll prepare a patch.

This is implemented in 1795974e6cc05b7f5edb07015dbd47e45b76fcef.

**Comment by oreiche** [comment]
@mhthies I have just pushed our proposal for building against distribution-specific shared libraries to my private fork: https://github.com/oreiche/justbuild/tree/system-deps

In a nutshell, the compile/link flags for system libraries are obtained via `pkg-config`:
- you can find the definitions in `etc/imports.pkgconfig`. There, the field `"name"` refers to the name of the package, in case ArchLinux uses different pkg-config file names
- the default path for package lookup is `LOCALBASE/share/pkgconfig` and `LOCALBASE/lib/pkgconfig`. You can set additional paths by setting the env variable ` PKG_CONFIG_PATH`

As you probably already know, all our dependencies are defined in `etc/repos.json`. Luckily on Debian 12 and Ubuntu 22.04 all of them are packaged already, except:
- the header-only library `gsl-lite`
- the protocol buffers from `google_apis` and `bazel_remote_apis`.

(Note that the missing archives can also pre-fetched to a `.distfiles` directory, using `bin/just-mr.py fetch <dep> -o .distfiles`)

To bootstrap against system libraries (except the missing ones), run `bin/bootstrap.py` with:
- `PACKAGE=YES`
- `LOCALBASE=/usr`
- `NON_LOCAL_DEPS='["gsl-lite","google_apis","bazel_remote_apis"]'`

The full process is demonstrated in this GitHub workflow: https://github.com/oreiche/justbuild/actions/runs/4680774041/jobs/8292529543

Please let us know what you think or if there is anything still missing. Many thanks!

**Comment by aehlig** [comment]
This approach has now been implemented, with amended bootstrap test in 29b9761d1da1906f5b952d4f6ac168c74a446fa9. So I believe this issue is fixed: only the names for the top-level `pkg-config` files have to be changed, if they differ in a given distribution.

If any problems remain, please file a new issue with details of the problems occurring when building against packaged dependencies using `pkg-config`.
